# Port Settings
server.port=${PORT:8080}
spring.thymeleaf.cache=false

# Database Configuration
spring.datasource.url=jdbc:postgresql://salemaster_db_user:eIq8xTlvhWUa3jqK6ppCKEXHIHZDCKXG@dpg-d85n2aegvqtc73e0gee0-a.singapore-postgres.render.com/salemaster_db
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate Optimization (No Metadata Scan)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# Connection Pool Limits for Memory Saving
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
