# Web Server Port
server.port=8080

# Thymeleaf Cache Disabled for Development
spring.thymeleaf.cache=false

# PostgreSQL Cloud Database Configuration (Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate Definite Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# মেটাডেটা চেকিং জ্যাম চিরতরে কাটানোর আলটিমেট লাইন
spring.jpa.hibernate.ddl-auto=create
