# Web Server Port
server.port=8080

# Thymeleaf Cache Disabled for Development
spring.thymeleaf.cache=false

# PostgreSQL Cloud Database Configuration (Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate Definite Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# হাইবারনেটের স্কিমা এক্সপোর্ট ও মেটাডেটা খোঁজা চিরতরে বন্ধ করার চূড়ান্ত ৩টি লাইন
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
